using NUnit.Framework;
using TMPro;
using UnityEditor;

namespace Pathweaver.Game.EditorTests
{
    /// <summary>
    /// The one font asset the game ships, and the properties of it that a player would notice
    /// breaking.
    /// </summary>
    /// <remarks>
    /// The asset is generated by <c>FontAssets.Build</c> and committed. These tests exist because
    /// every way it can go wrong is silent: a dropped glyph renders as a box, a dynamic atlas
    /// rasterises on the device instead, and a second atlas page costs a draw call per line of text.
    /// None of that shows up in a build log.
    /// </remarks>
    public class FontAssetTests
    {
        private const string FontAssetPath = "Assets/Fonts/VarelaRound SDF.asset";

        /// <summary>Printable Latin-1: 0x20 to 0x7E, then 0xA0 to 0xFF.</summary>
        private const int Latin1PrintableCount = (0x7E - 0x20 + 1) + (0xFF - 0xA0 + 1);

        /// <summary>The seven typographic marks Latin-1 lacks and the game's prose uses.</summary>
        private const string TypographicPunctuation = "\u2013\u2014\u2018\u2019\u201c\u201d\u2026";

        private static TMP_FontAsset Load()
        {
            var fontAsset = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(FontAssetPath);
            Assert.That(
                fontAsset,
                Is.Not.Null,
                $"No font asset at {FontAssetPath}. Rebuild it with FontAssets.Build.");

            return fontAsset;
        }

        [Test]
        public void The_font_asset_exists()
        {
            Assert.That(Load().name, Is.EqualTo("VarelaRound SDF"));
        }

        [Test]
        public void Every_printable_Latin1_character_is_in_the_atlas()
        {
            // 198 characters: 191 of Latin-1, plus seven marks. Anything short means glyphs were
            // dropped for want of atlas room, which is a box on a player's phone rather than an error
            // anywhere.
            Assert.That(
                Load().characterTable.Count,
                Is.EqualTo(Latin1PrintableCount + TypographicPunctuation.Length));
        }

        [Test]
        public void The_marks_the_prose_actually_uses_are_present()
        {
            // Found by rendering a preview sheet: "biome1-01 — First Waters" came out with a gap
            // where the em dash should be, because an em dash is U+2014 and the atlas stopped at
            // U+00FF. This project's writing uses em dashes constantly.
            foreach (var character in TypographicPunctuation)
            {
                Assert.That(
                    Load().HasCharacter(character),
                    Is.True,
                    $"The font asset has no glyph for U+{(int)character:X4}.");
            }
        }

        [Test]
        public void Spanish_and_English_both_render()
        {
            // The accented characters are the ones that got dropped the first time the atlas was
            // built, and the ones a Spanish string needs.
            foreach (var character in "abcXYZ0123áéíóúüñ¿¡")
            {
                Assert.That(
                    Load().HasCharacter(character),
                    Is.True,
                    $"The font asset has no glyph for '{character}'.");
            }
        }

        [Test]
        public void The_atlas_is_static()
        {
            // A dynamic atlas rasterises glyphs on the device the first time they are seen, which is
            // a stutter on the frame a number changes. The game's vocabulary is known at build time,
            // so there is nothing to gain by deferring it.
            Assert.That(Load().atlasPopulationMode, Is.EqualTo(AtlasPopulationMode.Static));
        }

        [Test]
        public void The_atlas_is_a_single_page()
        {
            // Two pages means two materials, which means a second draw call for a line of text.
            Assert.That(Load().atlasTextures.Length, Is.EqualTo(1));
        }

        [Test]
        public void The_atlas_and_its_material_are_saved_inside_the_asset()
        {
            // Both are created in memory and belong to nothing until they are added as sub-assets.
            // Left unsaved, the font asset references a null texture, which looks like a broken
            // shader rather than a missing file.
            var fontAsset = Load();

            Assert.That(fontAsset.atlasTexture, Is.Not.Null);
            Assert.That(fontAsset.material, Is.Not.Null);
            Assert.That(
                AssetDatabase.GetAssetPath(fontAsset.atlasTexture),
                Is.EqualTo(FontAssetPath),
                "The atlas texture is not a sub-asset of the font asset.");
            Assert.That(
                AssetDatabase.GetAssetPath(fontAsset.material),
                Is.EqualTo(FontAssetPath),
                "The material is not a sub-asset of the font asset.");
        }

        [Test]
        public void It_is_the_default_font_for_any_label()
        {
            // So a label that forgot to name a font gets the game's font rather than Liberation Sans.
            Assert.That(TMP_Settings.defaultFontAsset, Is.SameAs(Load()));
        }
    }
}
